
# this is the short identifier for the T2T
# plus hg002-Y used in the ONT-QC pipeline
# that produces some input for this pipeline:
# - cached coverages of whole-genome read alignments
# --- used to inform read subset selection for male assembly
input_qc_reference: T2TXYM


reference_genomes:
  T2TX: 'references_derived/T2T_chm13_122XM.fasta'
  T2TXY: 'references_derived/T2T_122XYM.fasta'
  GRCh38: ''
  hg38: ''  # placeholder for "only main chromosomes"


mbg_init_kmer:
  - 501
  - 501
  - 501
mbg_window_size:
  - 100
  - 100
  - 100
mbg_resolve_kmer:
  - 15001
  - 100001  # can only be used with ONTEC reads
  - 150001  # can only be used with ONTEC reads

# LJA is not used anymore
lja_small_kmer:
  - 501
lja_large_kmer:
  - 5001

# set synonyms for hifiasm
# output graphs to simplify
# file naming patterns
# Update: not used with Verkko
hifiasm_tig_names:
  UTGRAW: r_utg,
  UTGPRI: p_utg,
  CTGPRI: p_ctg,
  CTGALT: a_ctg