
reference_genomes:
  T2TX: 'references_derived/T2T_chm13_122XM.fasta'
  T2TXY: 'references_derived/T2T_122XYM.fasta'
  GRCh38: 'references_derived/GRCh38_noalt.fasta'
  hg38: ''  # placeholder for "only main chromosomes"

# chrY sequence classes: custom annotation created by Pille H.
# When stable, should be included in project repository
reference_y_seq_classes:
  T2TXY: T2T.chrY-seq-classes
  GRCh38: GRCh38_chrY-seq-classes_coord_plus_repeats

# annotation/input files created by Pille H.,
# are copied into the pipeline context when needed
expert_annotations:
  - T2T.chrY-seq-classes.bed
  - GRCh38.chrY-seq-classes.bed
  - GRCh38_chrY-seq-classes_coord_plus_repeats.bed
  - DYZ18_Yq.fasta
  - DYZ19_Yq.fasta
  - DYZ1_Yq.fasta
  - DYZ2_Yq.fasta
  - DYZ3-prim_Ycentro.fasta
  - DYZ3-sec_Ycentro.fasta
  - GRCh38_chrY-seq-classes_coord_plus_repeats.fasta
  - T2T.chrY-seq-classes.fasta
  - TSPY.fasta
  - Yqhet_2.7kb.fasta
  - Yqhet_3.1kb.fasta

motif_search:
  - DYZ18_Yq
  - DYZ1_Yq
  - DYZ2_Yq
  - DYZ19_Yq
  - DYZ3-prim_Ycentro
  - DYZ3-sec_Ycentro
  - TSPY
  - Yqhet_2.7kb
  - Yqhet_3.1kb

contig_id_motifs:
  - DYZ18_Yq
  - DYZ1_Yq
  - DYZ2_Yq
  - DYZ3-sec_Ycentro

# HMMER E-value cutoffs per motif,
# determined by expert (Pille H.)
# - discussions: see gh#5
hmmer_evalue_cutoff:
  'DYZ1_Yq': '1.60E-150'
  'DYZ18_Yq': '1.60E-150'
  'DYZ2_Yq': '1.60E-150'
  'DYZ3-sec_Ycentro': '1.60E-150'
  'DYZ3-prim_Ycentro': '1.60E-15'
  'DYZ19_Yq': '1.60E-15'
  'TSPY': '1.60E-200'
  'Yqhet_2.7kb': '1.60E-200'
  'Yqhey_3.1kb': '1.60E-200'

# HMMER score threshold per motif or 0,
# determined by expert (Pille H.)
# - discussions: see gh#5
hmmer_score_threshold:
  'DYZ1_Yq': 2500
  'DYZ18_Yq': 2100
  'DYZ2_Yq': 1700
  'DYZ3-sec_Ycentro': 1700
  'DYZ3-prim_Ycentro': 90
  'TSPY': 1000
  'Yqhet_2.7kb': 1500
  'Yqhet_3.1kb': 1500

# this info is part of the config
# just to populate the Globus share,
# it is not needed for a simple
# pipeline run
verkko_major: "1.0"
verkko_minor: "release"
#verkko_major: "1.0"
#verkko_minor: "beta2"
