
# this is the short identifier for the T2T
# plus hg002-Y used in the ONT-QC pipeline
# that produces some input for this pipeline:
# - cached coverages of whole-genome read alignments
# --- used to inform read subset selection for male assembly
# DEPRECATED: whole-genome runs by default now
input_qc_reference: T2TXYM


reference_genomes:
  T2TX: 'references_derived/T2T_chm13_122XM.fasta'
  T2TXY: 'references_derived/T2T_122XYM.fasta'
  GRCh38: 'references_derived/GRCh38_noalt.fasta'
  hg38: ''  # placeholder for "only main chromosomes"

# chrY sequence classes: custom annotation created by Pille H.
# i.e. need to be placed manually somewhere; if stable, should
# be included in project repository
reference_y_seq_classes:
  T2TXY: /gpfs/project/projects/medbioinf/data/share/globus/sig_chrY/references/T2T.chrY-seq-classes.bed
  GRCh38: /gpfs/project/projects/medbioinf/data/share/globus/sig_chrY/references/GRCh38.chrY-seq-classes.bed

motif_search:
  - DYZ18_Yq
  - DYZ1_Yq
  - DYZ2_Yq

verkko_major: "1.0"
verkko_minor: "beta2"

mbg_init_kmer:
  - 501
  - 501
  - 501
mbg_window_size:
  - 100
  - 100
  - 100
mbg_resolve_kmer:
  - 15001
  - 100001  # can only be used with ONTEC reads
  - 150001  # can only be used with ONTEC reads

# LJA is not used anymore
lja_small_kmer:
  - 501
lja_large_kmer:
  - 5001

# set synonyms for hifiasm
# output graphs to simplify
# file naming patterns
# Update: not used with Verkko
hifiasm_tig_names:
  UTGRAW: r_utg,
  UTGPRI: p_utg,
  CTGPRI: p_ctg,
  CTGALT: a_ctg